import { 
  Flower, 
  Map as MapIcon, 
  Scan, 
  User, 
  Home,
  Database, 
  Trophy, 
  Users, 
  Settings, 
  FlashlightOff as FlashOff, 
  LogOut, 
  Zap, 
  Info,
  ChevronRight,
  Camera,
  Search,
  X,
  Star,
  Sprout,
  Leaf,
  Clover,
  Flower2,
  Droplets,
  Bird,
  BookOpenCheck,
  Compass,
  Mountain,
  Microscope,
  Waves,
  Sunrise,
  PenTool,
  FlaskConical,
  ShieldCheck,
  Globe,
  Crown,
  Telescope,
  Medal
} from 'lucide-react';

export const Icons = {
  Home,
  Flower,
  Map: MapIcon,
  Scan,
  User,
  Collection: Database,
  Ranks: Trophy,
  Social: Users,
  Settings,
  FlashOff,
  LogOut,
  Zap,
  Info,
  ChevronRight,
  Camera,
  Search,
  X,
  Star,
  Sprout,
  Leaf,
  Clover,
  Flower2,
  Droplets,
  Bird,
  BookOpenCheck,
  Compass,
  Mountain,
  Microscope,
  Waves,
  Sunrise,
  PenTool,
  FlaskConical,
  ShieldCheck,
  Globe,
  Crown,
  Telescope,
  Medal
};

export type ScreenType = 'login' | 'home' | 'map' | 'scan' | 'collection' | 'ranks' | 'profile' | 'social';

export const FLOWER_IMAGES = {
  sunflowerView: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1000&q=80',
  sunflowerThumb: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=200&q=80',
  map: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1000&q=80',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80'
};
